version: '2'
services:
  tlog-backend:
    image: trainingproject/tlog16rs
    container_name: tlog-backend
    networks:
    - tlog
    ports:
    - "9080:8080"
    environment:
    - DB_USER=timelogger
    - DB_PASS=633Ym2aZ5b9Wtzh4EJc4pANx
    - DB_URL=jdbc:mariadb://tlog-db:3306/timelogger
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    networks:
    - tlog
    ports:
    - "9000:9000"
    - "9092:9092"
networks:
  tlog:
    driver: bridge
